/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface ComponentReportingDto {
  id?: string;
  nodeName?: string | null;
  nodePath?: string | null;
  nodeTarget?: string | null;
  componentId?: string;
}

export interface ComponentsGetTreeDataJsonQueryParams {
  performanceReportId?: string;
}

export type ComponentsGetTreeDataJsonProps = Omit<
  GetProps<string, unknown, ComponentsGetTreeDataJsonQueryParams, void>,
  'path'
>;

export const ComponentsGetTreeDataJson = (props: ComponentsGetTreeDataJsonProps) => (
  <Get<string, unknown, ComponentsGetTreeDataJsonQueryParams, void>
    path={`/api/v1/Epm/Components/GetTreeDataJson`}
    {...props}
  />
);

export type UseComponentsGetTreeDataJsonProps = Omit<
  UseGetProps<string, unknown, ComponentsGetTreeDataJsonQueryParams, void>,
  'path'
>;

export const useComponentsGetTreeDataJson = (props: UseComponentsGetTreeDataJsonProps) =>
  useGet<string, unknown, ComponentsGetTreeDataJsonQueryParams, void>(`/api/v1/Epm/Components/GetTreeDataJson`, props);

export interface ComponentsGetComponentReportingDetailsQueryParams {
  id?: string;
}

export type ComponentsGetComponentReportingDetailsProps = Omit<
  GetProps<ComponentReportingDto, unknown, ComponentsGetComponentReportingDetailsQueryParams, void>,
  'path'
>;

export const ComponentsGetComponentReportingDetails = (props: ComponentsGetComponentReportingDetailsProps) => (
  <Get<ComponentReportingDto, unknown, ComponentsGetComponentReportingDetailsQueryParams, void>
    path={`/api/v1/Epm/Components/GetComponentReportingDetails`}
    {...props}
  />
);

export type UseComponentsGetComponentReportingDetailsProps = Omit<
  UseGetProps<ComponentReportingDto, unknown, ComponentsGetComponentReportingDetailsQueryParams, void>,
  'path'
>;

export const useComponentsGetComponentReportingDetails = (props: UseComponentsGetComponentReportingDetailsProps) =>
  useGet<ComponentReportingDto, unknown, ComponentsGetComponentReportingDetailsQueryParams, void>(
    `/api/v1/Epm/Components/GetComponentReportingDetails`,
    props
  );
