/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface DynamicDtoHomeUrlRouteGuid {
  id?: string;
  deletionTime?: string | null;
  deleterUserId?: number | null;
  roles?: string;
  isDeleted?: boolean | null;
  creationTime?: string | null;
  homeUrl?: string;
  tenantId?: number | null;
  lastModifierUserId?: number | null;
  lastModificationTime?: string | null;
  creatorUserId?: number | null;
  orderIndex?: number | null;
  /**
   * List of form fields. Is used for partial updates. Contains a list of entity properties that should be updated. Leave empty to update all available entity fields
   */
  _formFields?: string[];
}

export interface DynamicDtoHomeUrlRouteGuidPagedResultDto {
  items?: DynamicDtoHomeUrlRouteGuid[] | null;
  totalCount?: number;
}

export interface ProxyDynamicDtoHomeUrlRouteGuid {
  id?: string;
  deletionTime?: string | null;
  deleterUserId?: number | null;
  roles?: string | null;
  isDeleted?: boolean | null;
  creationTime?: string | null;
  homeUrl?: string | null;
  tenantId?: number | null;
  lastModifierUserId?: number | null;
  lastModificationTime?: string | null;
  creatorUserId?: number | null;
  orderIndex?: number | null;
}

export interface HomeUrlRouteGetQueryParams {
  id?: string;
  'api-version'?: string;
}

export type HomeUrlRouteGetProps = Omit<
  GetProps<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteGetQueryParams, void>,
  'path'
>;

export const HomeUrlRouteGet = (props: HomeUrlRouteGetProps) => (
  <Get<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteGetQueryParams, void>
    path={`/api/services/Enterprise/HomeUrlRoute/Get`}
    {...props}
  />
);

export type UseHomeUrlRouteGetProps = Omit<
  UseGetProps<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteGetQueryParams, void>,
  'path'
>;

export const useHomeUrlRouteGet = (props: UseHomeUrlRouteGetProps) =>
  useGet<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteGetQueryParams, void>(
    `/api/services/Enterprise/HomeUrlRoute/Get`,
    props
  );

export interface HomeUrlRouteUpdateQueryParams {
  'api-version'?: string;
}

export type HomeUrlRouteUpdateProps = Omit<
  MutateProps<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteUpdateQueryParams, DynamicDtoHomeUrlRouteGuid, void>,
  'path' | 'verb'
>;

export const HomeUrlRouteUpdate = (props: HomeUrlRouteUpdateProps) => (
  <Mutate<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteUpdateQueryParams, DynamicDtoHomeUrlRouteGuid, void>
    verb="PUT"
    path={`/api/services/Enterprise/HomeUrlRoute/Update`}
    {...props}
  />
);

export type UseHomeUrlRouteUpdateProps = Omit<
  UseMutateProps<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteUpdateQueryParams, DynamicDtoHomeUrlRouteGuid, void>,
  'path' | 'verb'
>;

export const useHomeUrlRouteUpdate = (props: UseHomeUrlRouteUpdateProps) =>
  useMutate<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteUpdateQueryParams, DynamicDtoHomeUrlRouteGuid, void>(
    'PUT',
    `/api/services/Enterprise/HomeUrlRoute/Update`,
    props
  );

export interface HomeUrlRouteCreateQueryParams {
  'api-version'?: string;
}

export type HomeUrlRouteCreateProps = Omit<
  MutateProps<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteCreateQueryParams, DynamicDtoHomeUrlRouteGuid, void>,
  'path' | 'verb'
>;

export const HomeUrlRouteCreate = (props: HomeUrlRouteCreateProps) => (
  <Mutate<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteCreateQueryParams, DynamicDtoHomeUrlRouteGuid, void>
    verb="POST"
    path={`/api/services/Enterprise/HomeUrlRoute/Create`}
    {...props}
  />
);

export type UseHomeUrlRouteCreateProps = Omit<
  UseMutateProps<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteCreateQueryParams, DynamicDtoHomeUrlRouteGuid, void>,
  'path' | 'verb'
>;

export const useHomeUrlRouteCreate = (props: UseHomeUrlRouteCreateProps) =>
  useMutate<DynamicDtoHomeUrlRouteGuid, unknown, HomeUrlRouteCreateQueryParams, DynamicDtoHomeUrlRouteGuid, void>(
    'POST',
    `/api/services/Enterprise/HomeUrlRoute/Create`,
    props
  );

export interface HomeUrlRouteGetAllQueryParams {
  sorting?: string;
  skipCount?: number;
  maxResultCount?: number;
  'api-version'?: string;
}

export type HomeUrlRouteGetAllProps = Omit<
  GetProps<DynamicDtoHomeUrlRouteGuidPagedResultDto, unknown, HomeUrlRouteGetAllQueryParams, void>,
  'path'
>;

export const HomeUrlRouteGetAll = (props: HomeUrlRouteGetAllProps) => (
  <Get<DynamicDtoHomeUrlRouteGuidPagedResultDto, unknown, HomeUrlRouteGetAllQueryParams, void>
    path={`/api/services/Enterprise/HomeUrlRoute/GetAll`}
    {...props}
  />
);

export type UseHomeUrlRouteGetAllProps = Omit<
  UseGetProps<DynamicDtoHomeUrlRouteGuidPagedResultDto, unknown, HomeUrlRouteGetAllQueryParams, void>,
  'path'
>;

export const useHomeUrlRouteGetAll = (props: UseHomeUrlRouteGetAllProps) =>
  useGet<DynamicDtoHomeUrlRouteGuidPagedResultDto, unknown, HomeUrlRouteGetAllQueryParams, void>(
    `/api/services/Enterprise/HomeUrlRoute/GetAll`,
    props
  );

export interface HomeUrlRouteDeleteQueryParams {
  id?: string;
  'api-version'?: string;
}

export type HomeUrlRouteDeleteProps = Omit<
  MutateProps<void, unknown, HomeUrlRouteDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const HomeUrlRouteDelete = (props: HomeUrlRouteDeleteProps) => (
  <Mutate<void, unknown, HomeUrlRouteDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/Enterprise/HomeUrlRoute/Delete`}
    {...props}
  />
);

export type UseHomeUrlRouteDeleteProps = Omit<
  UseMutateProps<void, unknown, HomeUrlRouteDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useHomeUrlRouteDelete = (props: UseHomeUrlRouteDeleteProps) =>
  useMutate<void, unknown, HomeUrlRouteDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/Enterprise/HomeUrlRoute/Delete`,
    { ...props }
  );
