/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface MobileDeviceDto {
  id?: string;
  name?: string | null;
  imei?: string | null;
  isLocked?: boolean;
}

export interface MobileDeviceDtoPagedResultDto {
  items?: MobileDeviceDto[] | null;
  totalCount?: number;
}

export interface MobileDeviceGetQueryParams {
  id?: string;
  'api-version'?: string;
}

export type MobileDeviceGetProps = Omit<GetProps<MobileDeviceDto, unknown, MobileDeviceGetQueryParams, void>, 'path'>;

export const MobileDeviceGet = (props: MobileDeviceGetProps) => (
  <Get<MobileDeviceDto, unknown, MobileDeviceGetQueryParams, void>
    path={`/api/services/app/MobileDevice/Get`}
    {...props}
  />
);

export type UseMobileDeviceGetProps = Omit<
  UseGetProps<MobileDeviceDto, unknown, MobileDeviceGetQueryParams, void>,
  'path'
>;

export const useMobileDeviceGet = (props: UseMobileDeviceGetProps) =>
  useGet<MobileDeviceDto, unknown, MobileDeviceGetQueryParams, void>(`/api/services/app/MobileDevice/Get`, props);

export interface MobileDeviceGetAllQueryParams {
  sorting?: string;
  skipCount?: number;
  maxResultCount?: number;
  'api-version'?: string;
}

export type MobileDeviceGetAllProps = Omit<
  GetProps<MobileDeviceDtoPagedResultDto, unknown, MobileDeviceGetAllQueryParams, void>,
  'path'
>;

export const MobileDeviceGetAll = (props: MobileDeviceGetAllProps) => (
  <Get<MobileDeviceDtoPagedResultDto, unknown, MobileDeviceGetAllQueryParams, void>
    path={`/api/services/app/MobileDevice/GetAll`}
    {...props}
  />
);

export type UseMobileDeviceGetAllProps = Omit<
  UseGetProps<MobileDeviceDtoPagedResultDto, unknown, MobileDeviceGetAllQueryParams, void>,
  'path'
>;

export const useMobileDeviceGetAll = (props: UseMobileDeviceGetAllProps) =>
  useGet<MobileDeviceDtoPagedResultDto, unknown, MobileDeviceGetAllQueryParams, void>(
    `/api/services/app/MobileDevice/GetAll`,
    props
  );

export interface MobileDeviceCreateQueryParams {
  'api-version'?: string;
}

export type MobileDeviceCreateProps = Omit<
  MutateProps<MobileDeviceDto, unknown, MobileDeviceCreateQueryParams, MobileDeviceDto, void>,
  'path' | 'verb'
>;

export const MobileDeviceCreate = (props: MobileDeviceCreateProps) => (
  <Mutate<MobileDeviceDto, unknown, MobileDeviceCreateQueryParams, MobileDeviceDto, void>
    verb="POST"
    path={`/api/services/app/MobileDevice/Create`}
    {...props}
  />
);

export type UseMobileDeviceCreateProps = Omit<
  UseMutateProps<MobileDeviceDto, unknown, MobileDeviceCreateQueryParams, MobileDeviceDto, void>,
  'path' | 'verb'
>;

export const useMobileDeviceCreate = (props: UseMobileDeviceCreateProps) =>
  useMutate<MobileDeviceDto, unknown, MobileDeviceCreateQueryParams, MobileDeviceDto, void>(
    'POST',
    `/api/services/app/MobileDevice/Create`,
    props
  );

export interface MobileDeviceUpdateQueryParams {
  'api-version'?: string;
}

export type MobileDeviceUpdateProps = Omit<
  MutateProps<MobileDeviceDto, unknown, MobileDeviceUpdateQueryParams, MobileDeviceDto, void>,
  'path' | 'verb'
>;

export const MobileDeviceUpdate = (props: MobileDeviceUpdateProps) => (
  <Mutate<MobileDeviceDto, unknown, MobileDeviceUpdateQueryParams, MobileDeviceDto, void>
    verb="PUT"
    path={`/api/services/app/MobileDevice/Update`}
    {...props}
  />
);

export type UseMobileDeviceUpdateProps = Omit<
  UseMutateProps<MobileDeviceDto, unknown, MobileDeviceUpdateQueryParams, MobileDeviceDto, void>,
  'path' | 'verb'
>;

export const useMobileDeviceUpdate = (props: UseMobileDeviceUpdateProps) =>
  useMutate<MobileDeviceDto, unknown, MobileDeviceUpdateQueryParams, MobileDeviceDto, void>(
    'PUT',
    `/api/services/app/MobileDevice/Update`,
    props
  );

export interface MobileDeviceDeleteQueryParams {
  id?: string;
  'api-version'?: string;
}

export type MobileDeviceDeleteProps = Omit<
  MutateProps<void, unknown, MobileDeviceDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const MobileDeviceDelete = (props: MobileDeviceDeleteProps) => (
  <Mutate<void, unknown, MobileDeviceDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/MobileDevice/Delete`}
    {...props}
  />
);

export type UseMobileDeviceDeleteProps = Omit<
  UseMutateProps<void, unknown, MobileDeviceDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useMobileDeviceDelete = (props: UseMobileDeviceDeleteProps) =>
  useMutate<void, unknown, MobileDeviceDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/MobileDevice/Delete`,
    { ...props }
  );
