/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  displayText?: string | null;
}

export interface NotificationAttachmentDto {
  fileName?: string | null;
  storedFileId?: string;
}

export interface NotificationMessageDto {
  id?: string;
  sender?: GuidNullableEntityWithDisplayNameDto;
  recipient?: GuidNullableEntityWithDisplayNameDto;
  sendType?: ReferenceListItemValueDto;
  recipientText?: string | null;
  subject?: string | null;
  body?: string | null;
  template?: GuidNullableEntityWithDisplayNameDto;
  notification?: GuidNullableEntityWithDisplayNameDto;
  attachments?: NotificationAttachmentDto[] | null;
  sendDate?: string | null;
  tryCount?: number;
  status?: ReferenceListItemValueDto;
  errorMessage?: string | null;
}

export interface NotificationMessageDtoPagedResultDto {
  items?: NotificationMessageDto[] | null;
  totalCount?: number;
}

export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

export interface NotificationMessageResendQueryParams {
  id?: string;
  'api-version'?: string;
}

export type NotificationMessageResendProps = Omit<
  MutateProps<boolean, unknown, NotificationMessageResendQueryParams, void, void>,
  'path' | 'verb'
>;

export const NotificationMessageResend = (props: NotificationMessageResendProps) => (
  <Mutate<boolean, unknown, NotificationMessageResendQueryParams, void, void>
    verb="POST"
    path={`/api/services/app/NotificationMessage/Resend`}
    {...props}
  />
);

export type UseNotificationMessageResendProps = Omit<
  UseMutateProps<boolean, unknown, NotificationMessageResendQueryParams, void, void>,
  'path' | 'verb'
>;

export const useNotificationMessageResend = (props: UseNotificationMessageResendProps) =>
  useMutate<boolean, unknown, NotificationMessageResendQueryParams, void, void>(
    'POST',
    `/api/services/app/NotificationMessage/Resend`,
    props
  );

export interface NotificationMessageGetQueryParams {
  id?: string;
  'api-version'?: string;
}

export type NotificationMessageGetProps = Omit<
  GetProps<NotificationMessageDto, unknown, NotificationMessageGetQueryParams, void>,
  'path'
>;

export const NotificationMessageGet = (props: NotificationMessageGetProps) => (
  <Get<NotificationMessageDto, unknown, NotificationMessageGetQueryParams, void>
    path={`/api/services/app/NotificationMessage/Get`}
    {...props}
  />
);

export type UseNotificationMessageGetProps = Omit<
  UseGetProps<NotificationMessageDto, unknown, NotificationMessageGetQueryParams, void>,
  'path'
>;

export const useNotificationMessageGet = (props: UseNotificationMessageGetProps) =>
  useGet<NotificationMessageDto, unknown, NotificationMessageGetQueryParams, void>(
    `/api/services/app/NotificationMessage/Get`,
    props
  );

export interface NotificationMessageGetAllQueryParams {
  sorting?: string;
  skipCount?: number;
  maxResultCount?: number;
  'api-version'?: string;
}

export type NotificationMessageGetAllProps = Omit<
  GetProps<NotificationMessageDtoPagedResultDto, unknown, NotificationMessageGetAllQueryParams, void>,
  'path'
>;

export const NotificationMessageGetAll = (props: NotificationMessageGetAllProps) => (
  <Get<NotificationMessageDtoPagedResultDto, unknown, NotificationMessageGetAllQueryParams, void>
    path={`/api/services/app/NotificationMessage/GetAll`}
    {...props}
  />
);

export type UseNotificationMessageGetAllProps = Omit<
  UseGetProps<NotificationMessageDtoPagedResultDto, unknown, NotificationMessageGetAllQueryParams, void>,
  'path'
>;

export const useNotificationMessageGetAll = (props: UseNotificationMessageGetAllProps) =>
  useGet<NotificationMessageDtoPagedResultDto, unknown, NotificationMessageGetAllQueryParams, void>(
    `/api/services/app/NotificationMessage/GetAll`,
    props
  );

export interface NotificationMessageCreateQueryParams {
  'api-version'?: string;
}

export type NotificationMessageCreateProps = Omit<
  MutateProps<NotificationMessageDto, unknown, NotificationMessageCreateQueryParams, NotificationMessageDto, void>,
  'path' | 'verb'
>;

export const NotificationMessageCreate = (props: NotificationMessageCreateProps) => (
  <Mutate<NotificationMessageDto, unknown, NotificationMessageCreateQueryParams, NotificationMessageDto, void>
    verb="POST"
    path={`/api/services/app/NotificationMessage/Create`}
    {...props}
  />
);

export type UseNotificationMessageCreateProps = Omit<
  UseMutateProps<NotificationMessageDto, unknown, NotificationMessageCreateQueryParams, NotificationMessageDto, void>,
  'path' | 'verb'
>;

export const useNotificationMessageCreate = (props: UseNotificationMessageCreateProps) =>
  useMutate<NotificationMessageDto, unknown, NotificationMessageCreateQueryParams, NotificationMessageDto, void>(
    'POST',
    `/api/services/app/NotificationMessage/Create`,
    props
  );

export interface NotificationMessageUpdateQueryParams {
  'api-version'?: string;
}

export type NotificationMessageUpdateProps = Omit<
  MutateProps<NotificationMessageDto, unknown, NotificationMessageUpdateQueryParams, NotificationMessageDto, void>,
  'path' | 'verb'
>;

export const NotificationMessageUpdate = (props: NotificationMessageUpdateProps) => (
  <Mutate<NotificationMessageDto, unknown, NotificationMessageUpdateQueryParams, NotificationMessageDto, void>
    verb="PUT"
    path={`/api/services/app/NotificationMessage/Update`}
    {...props}
  />
);

export type UseNotificationMessageUpdateProps = Omit<
  UseMutateProps<NotificationMessageDto, unknown, NotificationMessageUpdateQueryParams, NotificationMessageDto, void>,
  'path' | 'verb'
>;

export const useNotificationMessageUpdate = (props: UseNotificationMessageUpdateProps) =>
  useMutate<NotificationMessageDto, unknown, NotificationMessageUpdateQueryParams, NotificationMessageDto, void>(
    'PUT',
    `/api/services/app/NotificationMessage/Update`,
    props
  );

export interface NotificationMessageDeleteQueryParams {
  id?: string;
  'api-version'?: string;
}

export type NotificationMessageDeleteProps = Omit<
  MutateProps<void, unknown, NotificationMessageDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const NotificationMessageDelete = (props: NotificationMessageDeleteProps) => (
  <Mutate<void, unknown, NotificationMessageDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/NotificationMessage/Delete`}
    {...props}
  />
);

export type UseNotificationMessageDeleteProps = Omit<
  UseMutateProps<void, unknown, NotificationMessageDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useNotificationMessageDelete = (props: UseNotificationMessageDeleteProps) =>
  useMutate<void, unknown, NotificationMessageDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/NotificationMessage/Delete`,
    { ...props }
  );
