/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface OtpAuditItemDto {
  id?: string;
  creationTime?: string;
  sendTo?: string | null;
  sendType?: ReferenceListItemValueDto;
  recipientType?: string | null;
  recipientId?: string | null;
  expiresOn?: string | null;
  otp?: string | null;
  actionType?: string | null;
  sentOn?: string | null;
  sendStatus?: ReferenceListItemValueDto;
  errorMessage?: string | null;
}

export interface OtpAuditItemDtoPagedResultDto {
  items?: OtpAuditItemDto[] | null;
  totalCount?: number;
}

export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

export interface OtpAuditItemGetQueryParams {
  id?: string;
  'api-version'?: string;
}

export type OtpAuditItemGetProps = Omit<GetProps<OtpAuditItemDto, unknown, OtpAuditItemGetQueryParams, void>, 'path'>;

export const OtpAuditItemGet = (props: OtpAuditItemGetProps) => (
  <Get<OtpAuditItemDto, unknown, OtpAuditItemGetQueryParams, void>
    path={`/api/services/app/OtpAuditItem/Get`}
    {...props}
  />
);

export type UseOtpAuditItemGetProps = Omit<
  UseGetProps<OtpAuditItemDto, unknown, OtpAuditItemGetQueryParams, void>,
  'path'
>;

export const useOtpAuditItemGet = (props: UseOtpAuditItemGetProps) =>
  useGet<OtpAuditItemDto, unknown, OtpAuditItemGetQueryParams, void>(`/api/services/app/OtpAuditItem/Get`, props);

export interface OtpAuditItemGetAllQueryParams {
  sorting?: string;
  skipCount?: number;
  maxResultCount?: number;
  'api-version'?: string;
}

export type OtpAuditItemGetAllProps = Omit<
  GetProps<OtpAuditItemDtoPagedResultDto, unknown, OtpAuditItemGetAllQueryParams, void>,
  'path'
>;

export const OtpAuditItemGetAll = (props: OtpAuditItemGetAllProps) => (
  <Get<OtpAuditItemDtoPagedResultDto, unknown, OtpAuditItemGetAllQueryParams, void>
    path={`/api/services/app/OtpAuditItem/GetAll`}
    {...props}
  />
);

export type UseOtpAuditItemGetAllProps = Omit<
  UseGetProps<OtpAuditItemDtoPagedResultDto, unknown, OtpAuditItemGetAllQueryParams, void>,
  'path'
>;

export const useOtpAuditItemGetAll = (props: UseOtpAuditItemGetAllProps) =>
  useGet<OtpAuditItemDtoPagedResultDto, unknown, OtpAuditItemGetAllQueryParams, void>(
    `/api/services/app/OtpAuditItem/GetAll`,
    props
  );

export interface OtpAuditItemCreateQueryParams {
  'api-version'?: string;
}

export type OtpAuditItemCreateProps = Omit<
  MutateProps<OtpAuditItemDto, unknown, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const OtpAuditItemCreate = (props: OtpAuditItemCreateProps) => (
  <Mutate<OtpAuditItemDto, unknown, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>
    verb="POST"
    path={`/api/services/app/OtpAuditItem/Create`}
    {...props}
  />
);

export type UseOtpAuditItemCreateProps = Omit<
  UseMutateProps<OtpAuditItemDto, unknown, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const useOtpAuditItemCreate = (props: UseOtpAuditItemCreateProps) =>
  useMutate<OtpAuditItemDto, unknown, OtpAuditItemCreateQueryParams, OtpAuditItemDto, void>(
    'POST',
    `/api/services/app/OtpAuditItem/Create`,
    props
  );

export interface OtpAuditItemUpdateQueryParams {
  'api-version'?: string;
}

export type OtpAuditItemUpdateProps = Omit<
  MutateProps<OtpAuditItemDto, unknown, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const OtpAuditItemUpdate = (props: OtpAuditItemUpdateProps) => (
  <Mutate<OtpAuditItemDto, unknown, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>
    verb="PUT"
    path={`/api/services/app/OtpAuditItem/Update`}
    {...props}
  />
);

export type UseOtpAuditItemUpdateProps = Omit<
  UseMutateProps<OtpAuditItemDto, unknown, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>,
  'path' | 'verb'
>;

export const useOtpAuditItemUpdate = (props: UseOtpAuditItemUpdateProps) =>
  useMutate<OtpAuditItemDto, unknown, OtpAuditItemUpdateQueryParams, OtpAuditItemDto, void>(
    'PUT',
    `/api/services/app/OtpAuditItem/Update`,
    props
  );

export interface OtpAuditItemDeleteQueryParams {
  id?: string;
  'api-version'?: string;
}

export type OtpAuditItemDeleteProps = Omit<
  MutateProps<void, unknown, OtpAuditItemDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const OtpAuditItemDelete = (props: OtpAuditItemDeleteProps) => (
  <Mutate<void, unknown, OtpAuditItemDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/OtpAuditItem/Delete`}
    {...props}
  />
);

export type UseOtpAuditItemDeleteProps = Omit<
  UseMutateProps<void, unknown, OtpAuditItemDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useOtpAuditItemDelete = (props: UseOtpAuditItemDeleteProps) =>
  useMutate<void, unknown, OtpAuditItemDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/OtpAuditItem/Delete`,
    { ...props }
  );
