/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface FlattenedAllowedComponentTypesDto {
  id?: string;
  formPath?: string | null;
  componentTypeId?: string;
  componentTypeName?: string | null;
  canBeRoot?: boolean;
}

export interface PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdQueryParams {
  id?: string;
  parentComponentId?: string;
}

export type PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdProps = Omit<
  GetProps<
    FlattenedAllowedComponentTypesDto[],
    unknown,
    PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdQueryParams,
    void
  >,
  'path'
>;

export const PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateId = (
  props: PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdProps
) => (
  <Get<
    FlattenedAllowedComponentTypesDto[],
    unknown,
    PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdQueryParams,
    void
  >
    path={`/api/v1/Epm/PerformanceReportAllowedComponentTypes/GetFlattenedAllowedComponentTypesByTemplateId`}
    {...props}
  />
);

export type UsePerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdProps = Omit<
  UseGetProps<
    FlattenedAllowedComponentTypesDto[],
    unknown,
    PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdQueryParams,
    void
  >,
  'path'
>;

export const usePerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateId = (
  props: UsePerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdProps
) =>
  useGet<
    FlattenedAllowedComponentTypesDto[],
    unknown,
    PerformanceReportAllowedComponentTypesGetFlattenedAllowedComponentTypesByTemplateIdQueryParams,
    void
  >(`/api/v1/Epm/PerformanceReportAllowedComponentTypes/GetFlattenedAllowedComponentTypesByTemplateId`, props);
