/* Generated by restful-react */

import React from 'react';
import { Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface DynamicDtoProgressReportGuid {
  id?: string;
  /**
   * List of form fields. Is used for partial updates. Contains a list of entity properties that should be updated. Leave empty to update all available entity fields
   */
  _formFields?: string[];
  performanceReport?: string | null;
  periodCovered?: string | null;
  lastModifierUserId?: number | null;
  status?: number | null;
  deletionTime?: string | null;
  creationTime?: string | null;
  creatorUserId?: number | null;
  lastModificationTime?: string | null;
  isDeleted?: boolean | null;
  deleterUserId?: number | null;
  _meta?: MetaDto;
}

export type JToken = JToken[];

export interface MetaDto {
  className?: string | null;
}

export interface ProxyDynamicDtoProgressReportGuid {
  id?: string;
  jObject?: {
    [key: string]: JToken;
  } | null;
  performanceReport?: string | null;
  periodCovered?: string | null;
  lastModifierUserId?: number | null;
  status?: number | null;
  deletionTime?: string | null;
  creationTime?: string | null;
  creatorUserId?: number | null;
  lastModificationTime?: string | null;
  isDeleted?: boolean | null;
  deleterUserId?: number | null;
  _meta?: MetaDto;
}

export interface ProgressReportsPublishProgressReportPathParams {
  progressReportId: string;
}

export type ProgressReportsPublishProgressReportProps = Omit<
  MutateProps<DynamicDtoProgressReportGuid, unknown, void, void, ProgressReportsPublishProgressReportPathParams>,
  'path' | 'verb'
> &
  ProgressReportsPublishProgressReportPathParams;

export const ProgressReportsPublishProgressReport = ({
  progressReportId,
  ...props
}: ProgressReportsPublishProgressReportProps) => (
  <Mutate<DynamicDtoProgressReportGuid, unknown, void, void, ProgressReportsPublishProgressReportPathParams>
    verb="PUT"
    path={`/api/v1/Epm/ProgressReports/${progressReportId}/PublishProgressReport`}
    {...props}
  />
);

export type UseProgressReportsPublishProgressReportProps = Omit<
  UseMutateProps<DynamicDtoProgressReportGuid, unknown, void, void, ProgressReportsPublishProgressReportPathParams>,
  'path' | 'verb'
> &
  ProgressReportsPublishProgressReportPathParams;

export const useProgressReportsPublishProgressReport = ({
  progressReportId,
  ...props
}: UseProgressReportsPublishProgressReportProps) =>
  useMutate<DynamicDtoProgressReportGuid, unknown, void, void, ProgressReportsPublishProgressReportPathParams>(
    'PUT',
    (paramsInPath: ProgressReportsPublishProgressReportPathParams) =>
      `/api/v1/Epm/ProgressReports/${paramsInPath.progressReportId}/PublishProgressReport`,
    { pathParams: { progressReportId }, ...props }
  );
