/* Generated by restful-react */

import React from 'react';
import { Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface ActionResult {
  [key: string]: any;
}

export interface ActionResultAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ActionResult;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ReportDesignerGetReportDesignerModelQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type ReportDesignerGetReportDesignerModelProps = Omit<
  MutateProps<ActionResultAjaxResponse, AjaxResponseBase, ReportDesignerGetReportDesignerModelQueryParams, void, void>,
  'path' | 'verb'
>;

export const ReportDesignerGetReportDesignerModel = (props: ReportDesignerGetReportDesignerModelProps) => (
  <Mutate<ActionResultAjaxResponse, AjaxResponseBase, ReportDesignerGetReportDesignerModelQueryParams, void, void>
    verb="POST"
    path={`/api/ReportDesigner/GetReportDesignerModel`}
    {...props}
  />
);

export type UseReportDesignerGetReportDesignerModelProps = Omit<
  UseMutateProps<
    ActionResultAjaxResponse,
    AjaxResponseBase,
    ReportDesignerGetReportDesignerModelQueryParams,
    void,
    void
  >,
  'path' | 'verb'
>;

export const useReportDesignerGetReportDesignerModel = (props: UseReportDesignerGetReportDesignerModelProps) =>
  useMutate<ActionResultAjaxResponse, AjaxResponseBase, ReportDesignerGetReportDesignerModelQueryParams, void, void>(
    'POST',
    `/api/ReportDesigner/GetReportDesignerModel`,
    props
  );
